// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  applyGoogleGeminiModelDefault,
  DEFAULT_GOOGLE_API_BASE_URL,
  GOOGLE_GEMINI_DEFAULT_MODEL,
  isGoogleGenerativeAiApi,
  normalizeAntigravityModelId,
  normalizeGoogleApiBaseUrl,
  normalizeGoogleGenerativeAiBaseUrl,
  normalizeGoogleModelId,
  normalizeGoogleProviderConfig,
  parseGeminiAuth,
  resolveGoogleGenerativeAiApiOrigin,
  resolveGoogleGenerativeAiTransport,
  shouldNormalizeGoogleGenerativeAiProviderConfig,
  shouldNormalizeGoogleProviderConfig,
} from "../../extensions/google/api.js";
